export const New=[
  {
    id: 15,
    title: "Classic White Creqqqw Neck T-Shirt",
    price: 39,
    description:
      "Elevate your basics with this versatile white crew neck tee. Made from a soft, breathable cotton blend, it offers both comfort and durability. Its sleek, timelesqqqqqs design ensures it pairs well with virtually any outfit. Ideal for layering or wearing on its own, this t-shirt is a must-have staple for every wardrobe.",
    images: ['https://i.imgur.com/axsyGpD.jpeg'],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-03T15:23:02.000Z",
    category: {
      id: 1,
      name: "Clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 25,
    title: "Stylish Red & Silver Over-Ear Headphones",
    price: 39,
    description:
      "Immerse yourself in superior sound quality with these sleek red and silver over-ear headphones. Designed for comfort and style, the headphones feature cushioned ear cups, an adjustable padded headband, and a detachable red cable for easy storage and portability. Perfect for music lovers and audiophiles who value both appearance and audio fidelity.",
    images: [
      "https://i.imgur.com/YaSqa06.jpeg",
      "https://i.imgur.com/isQAliJ.jpeg",
      "https://i.imgur.com/5B8UQfh.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 2,
      name: "Electronics",
      image: "https://i.imgur.com/ZANVnHE.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 27,
    title: "Sleek Smartwatch with Vibrant Display",
    price: 16,
    description:
      "Experience modern timekeeping with our high-tech smartwatch, featuring a vivid touch screen display, customizable watch faces, and a comfortable blue silicone strap. This smartwatch keeps you connected with notifications and fitness tracking while showcasing exceptional style and versatility.",
    images: [
      "https://i.imgur.com/LGk9Jn2.jpeg",
      "https://i.imgur.com/1ttYWaI.jpeg",
      "https://i.imgur.com/sPRWnJH.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 2,
      name: "Electronics",
      image: "https://i.imgur.com/ZANVnHE.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 29,
    title: "Mid-Century Modern Wooden Dining Table",
    price: 24,
    description:
      "Elevate your dining room with this sleek Mid-Century Modern dining table, featuring an elegant walnut finish and tapered legs for a timeless aesthetic. Its sturdy wood construction and minimalist design make it a versatile piece that fits with a variety of decor styles. Perfect for intimate dinners or as a stylish spot for your morning coffee.",
    images: [
      "https://i.imgur.com/DMQHGA0.jpeg",
      "https://i.imgur.com/qrs9QBg.jpeg",
      "https://i.imgur.com/XVp8T1I.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 3,
      name: "Musa",
      image: "https://i.imgur.com/Qphac99.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-03T11:53:25.000Z",
    },
  },
  {
    id: 30,
    title: "Elegant Golden-Base Stone Top Dining Table",
    price: 66,
    description:
      "Elevate your dining space with this luxurious table, featuring a sturdy golden metal base with an intricate rod design that provides both stability and chic elegance. The smooth stone top in a sleek round shape offers a robust surface for your dining pleasure. Perfect for both everyday meals and special occasions, this table easily complements any modern or glam decor.",
    images: [
      "https://i.imgur.com/NWIJKUj.jpeg",
      "https://i.imgur.com/Jn1YSLk.jpeg",
      "https://i.imgur.com/VNZRvx5.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 3,
      name: "Musa",
      image: "https://i.imgur.com/Qphac99.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-03T11:53:25.000Z",
    },
  },
  {
    id: 31,
    title: "Modern Elegance Teal Armchair",
    price: 25,
    description:
      "Elevate your living space with this beautifully crafted armchair, featuring a sleek wooden frame that complements its vibrant teal upholstery. Ideal for adding a pop of color and contemporary style to any room, this chair provides both superb comfort and sophisticated design. Perfect for reading, relaxing, or creating a cozy conversation nook.",
    images: [
      "https://i.imgur.com/6wkyyIN.jpeg",
      "https://i.imgur.com/Ald3Rec.jpeg",
      "https://i.imgur.com/dIqo03c.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 3,
      name: "Musa",
      image: "https://i.imgur.com/Qphac99.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-03T11:53:25.000Z",
    },
  },
  {
    id: 32,
    title: "Elegant Solid Wood Dining Table",
    price: 67,
    description:
      "Enhance your dining space with this sleek, contemporary dining table, crafted from high-quality solid wood with a warm finish. Its sturdy construction and minimalist design make it a perfect addition for any home looking for a touch of elegance. Accommodates up to six guests comfortably and includes a striking fruit bowl centerpiece. The overhead lighting is not included.",
    images: [
      "https://i.imgur.com/4lTaHfF.jpeg",
      "https://i.imgur.com/JktHE1C.jpeg",
      "https://i.imgur.com/cQeXQMi.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 3,
      name: "Musa",
      image: "https://i.imgur.com/Qphac99.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-03T11:53:25.000Z",
    },
  },
  {
    id: 33,
    title: "Modern Minimalist Workstation Setup",
    price: 49,
    description:
      "Elevate your home office with our Modern Minimalist Workstation Setup, featuring a sleek wooden desk topped with an elegant computer, stylish adjustable wooden desk lamp, and complimentary accessories for a clean, productive workspace. This setup is perfect for professionals seeking a contemporary look that combines functionality with design.",
    images: [
      "https://i.imgur.com/3oXNBst.jpeg",
      "https://i.imgur.com/ErYYZnT.jpeg",
      "https://i.imgur.com/boBPwYW.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 3,
      name: "Musa",
      image: "https://i.imgur.com/Qphac99.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-03T11:53:25.000Z",
    },
  },
  {
    id: 34,
    title: "Modern Ergonomic Office Chair",
    price: 71,
    description:
      "Elevate your office space with this sleek and comfortable Modern Ergonomic Office Chair. Designed to provide optimal support throughout the workday, it features an adjustable height mechanism, smooth-rolling casters for easy mobility, and a cushioned seat for extended comfort. The clean lines and minimalist white design make it a versatile addition to any contemporary workspace.",
    images: [
      "https://i.imgur.com/3dU0m72.jpeg",
      "https://i.imgur.com/zPU3EVa.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 3,
      name: "Musa",
      image: "https://i.imgur.com/Qphac99.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-03T11:53:25.000Z",
    },
  },
  {
    id: 37,
    title: "Chic Summer Denim Espadrille Sandals",
    price: 33,
    description:
      "Step into summer with style in our denim espadrille sandals. Featuring a braided jute sole for a classic touch and adjustable denim straps for a snug fit, these sandals offer both comfort and a fashionable edge. The easy slip-on design ensures convenience for beach days or casual outings.",
    images: [
      "https://i.imgur.com/9qrmE1b.jpeg",
      "https://i.imgur.com/wqKxBVH.jpeg",
      "https://i.imgur.com/sWSV6DK.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 4,
      name: "Shoes",
      image: "https://i.imgur.com/qNOjJje.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 38,
    title: "Vibrant Runners: Bold Orange & Blue Sneakers",
    price: 27,
    description:
      "Step into style with these eye-catching sneakers featuring a striking combination of orange and blue hues. Designed for both comfort and fashion, these shoes come with flexible soles and cushioned insoles, perfect for active individuals who don't compromise on style. The reflective silver accents add a touch of modernity, making them a standout accessory for your workout or casual wear.",
    images: [
      "https://i.imgur.com/hKcMNJs.jpeg",
      "https://i.imgur.com/NYToymX.jpeg",
      "https://i.imgur.com/HiiapCt.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 4,
      name: "Shoes",
      image: "https://i.imgur.com/qNOjJje.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 39,
    title: "Vibrant Pink Classic Sneakers",
    price: 84,
    description:
      "Step into style with our Vibrant Pink Classic Sneakers! These eye-catching shoes feature a bold pink hue with iconic white detailing, offering a sleek, timeless design. Constructed with durable materials and a comfortable fit, they are perfect for those seeking a pop of color in their everyday footwear. Grab a pair today and add some vibrancy to your step!",
    images: [
      "https://i.imgur.com/mcW42Gi.jpeg",
      "https://i.imgur.com/mhn7qsF.jpeg",
      "https://i.imgur.com/F8vhnFJ.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 4,
      name: "Shoes",
      image: "https://i.imgur.com/qNOjJje.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 40,
    title: "Futuristic Silver and Gold High-Top Sneaker",
    price: 68,
    description:
      "Step into the future with this eye-catching high-top sneaker, designed for those who dare to stand out. The sneaker features a sleek silver body with striking gold accents, offering a modern twist on classic footwear. Its high-top design provides support and style, making it the perfect addition to any avant-garde fashion collection. Grab a pair today and elevate your shoe game!",
    images: [
      "https://i.imgur.com/npLfCGq.jpeg",
      "https://i.imgur.com/vYim3gj.jpeg",
      "https://i.imgur.com/HxuHwBO.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 4,
      name: "Shoes",
      image: "https://i.imgur.com/qNOjJje.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 41,
    title: "Futuristic Chic High-Heel Boots",
    price: 36,
    description:
      "Elevate your style with our cutting-edge high-heel boots that blend bold design with avant-garde aesthetics. These boots feature a unique color-block heel, a sleek silhouette, and a versatile light grey finish that pairs easily with any cutting-edge outfit. Crafted for the fashion-forward individual, these boots are sure to make a statement.",
    images: [
      "https://i.imgur.com/HqYqLnW.jpeg",
      "https://i.imgur.com/RlDGnZw.jpeg",
      "https://i.imgur.com/qa0O6fg.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 4,
      name: "Shoes",
      image: "https://i.imgur.com/qNOjJje.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 43,
    title: "Elegant Purple Leather Loafers",
    price: 17,
    description:
      "Step into sophistication with our Elegant Purple Leather Loafers, perfect for making a bold statement. Crafted from high-quality leather with a vibrant purple finish, these shoes feature a classic loafer silhouette that's been updated with a contemporary twist. The comfortable slip-on design and durable soles ensure both style and functionality for the modern man.",
    images: [
      "https://i.imgur.com/Au8J9sX.jpeg",
      "https://i.imgur.com/gdr8BW2.jpeg",
      "https://i.imgur.com/KDCZxnJ.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 4,
      name: "Shoes",
      image: "https://i.imgur.com/qNOjJje.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 44,
    title: "Classic Blue Suede Casual Shoes",
    price: 39,
    description:
      "Step into comfort with our Classic Blue Suede Casual Shoes, perfect for everyday wear. These shoes feature a stylish blue suede upper, durable rubber soles for superior traction, and classic lace-up fronts for a snug fit. The sleek design pairs well with both jeans and chinos, making them a versatile addition to any wardrobe.",
    images: [
      "https://i.imgur.com/sC0ztOB.jpeg",
      "https://i.imgur.com/Jf9DL9R.jpeg",
      "https://i.imgur.com/R1IN95T.jpeg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 4,
      name: "Shoes",
      image: "https://i.imgur.com/qNOjJje.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 45,
    title: "Sleek Futuristic Electric Bicycle",
    price: 22,
    description:
      "This modern electric bicycle combines style and efficiency with its unique design and top-notch performance features. Equipped with a durable frame, enhanced battery life, and integrated tech capabilities, it's perfect for the eco-conscious commuter looking to navigate the city with ease.",
    images: [
      "https://i.imgur.com/BG8J0Fj.jpg",
      "https://i.imgur.com/ujHBpCX.jpg",
      "https://i.imgur.com/WHeVL9H.jpg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 5,
      name: "Miscellaneous",
      image: "https://i.imgur.com/BG8J0Fj.jpg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 47,
    title: "otro cambio",
    price: 332,
    description:
      "Indulge in the essence of summer with this vibrant citrus-scented Eau de Parfum. Encased in a sleek glass bottle with a bold orange cap, this fragrance embodies freshness and elegance. Perfect for daily wear, it's an olfactory delight that leaves a lasting, zesty impression.",
    images: [
      "https://i.imgur.com/xPDwUb3.jpg",
      "https://i.imgur.com/3rfp691.jpg",
      "https://i.imgur.com/kG05a29.jpg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-03T00:17:43.000Z",
    category: {
      id: 5,
      name: "Miscellaneous",
      image: "https://i.imgur.com/BG8J0Fj.jpg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 49,
    title: "Chic Transparent Fashion Handbag",
    price: 61,
    description:
      "Elevate your style with our Chic Transparent Fashion Handbag, perfect for showcasing your essentials with a clear, modern edge. This trendy accessory features durable acrylic construction, luxe gold-tone hardware, and an elegant chain strap. Its compact size ensures you can carry your day-to-day items with ease and sophistication.",
    images: [
      "https://i.imgur.com/Lqaqz59.jpg",
      "https://i.imgur.com/uSqWK0m.jpg",
      "https://i.imgur.com/atWACf1.jpg",
    ],
    creationAt: "2024-03-02T17:12:25.000Z",
    updatedAt: "2024-03-02T17:12:25.000Z",
    category: {
      id: 5,
      name: "Miscellaneous",
      image: "https://i.imgur.com/BG8J0Fj.jpg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  {
    id: 79,
    title: "new p pruebaaa",
    price: 120,
    description: "new",
    images: ["https://i.imgur.com/cSytoSD.jpeg"],
    creationAt: "2024-03-03T09:59:24.000Z",
    updatedAt: "2024-03-03T09:59:24.000Z",
    category: {
      id: 5,
      name: "Miscellaneous",
      image: "https://i.imgur.com/BG8J0Fj.jpg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  },
  
  {
    id: 81,
    title: "Tesla AI BIke",
    price: 234,
    description: "New Bike ",
    images: [
      "https://i.imgur.com/3oXNBst.jpeghttps://i.imgur.com/ErYYZnT.jpeghttps://i.imgur.com/boBPwYW.jpeg",
    ],
    creationAt: "2024-03-03T11:12:11.000Z",
    updatedAt: "2024-03-03T11:15:51.000Z",
    category: {
      id: 1,
      name: "Clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2024-03-02T17:12:25.000Z",
      updatedAt: "2024-03-02T17:12:25.000Z",
    },
  }
];
